version: "3"
services: 
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: skhan1211/litflix
    volumes:
      - .:/Litflix
    ports:
      - "3000:3000"
    depends_on: 
      - db
    environment:
      DATABASE_URL: postgres://postgres@db      